apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-prod

spec:
  storageClassName: manual
  capacity:
    storage: 20Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/prod/mongo"
