apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-dev

spec:
  storageClassName: manual
  capacity:
    storage: 20Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/dev/mongo"
